### ISSUE TITLE
The emulator does not appear in the noVNC

### ISSUE THREAD

**Issue by ruycostajr** [budtmo/docker-android#120] opened 2018-09-14 19:03 UTC
Operating System: 
Ubuntu 14.04 LTS x64

Docker Image:
butomo1989/docker-android-x86-7.1.1, butomo1989/docker-android-real-device

Docker Version:  
18.03.0-ce, build 0520e24

Docker-compose version (Only if you use it):  
1.20.1, build 5d8c71b

Docker Command to start docker-android:  
docker-compose up -d

## Actual Behavior
The noVnc connects but the screen goes blank, only the appium terminal appears,
![docker-android](https://user-images.githubusercontent.com/26141090/45569860-36fc0c00-b837-11e8-9adf-4d8c2d0a63b1.png)
 

CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                      PORTS                                             NAMES
6794404f06f7        butomo1989/docker-android-x86-7.1.1   "/bin/sh -c '/usr/biâ¦"   47 seconds ago      Up 46 seconds (unhealthy)   4723/tcp, 5554-5555/tcp, 0.0.0.0:6080->6080/tcp   android_nexus_7.1.1_1
0a92dc093b0a        appium/appium                         "/bin/sh -c '/root/wâ¦"   48 seconds ago      Up 47 seconds                                                                 android_real_device_1
2b13d06abd7a        selenium/hub:3.14.0-curium            "/opt/bin/entry_poinâ¦"   49 seconds ago      Up 47 seconds               0.0.0.0:4444->4444/tcp                            android_selenium_hub_1

Log from container
2018-09-14 11:36:36,143 CRIT Supervisor running as root (no user in config file)
2018-09-14 11:36:36,146 INFO supervisord started with pid 7
2018-09-14 11:36:37,149 INFO spawned: 'xvfb' with pid 10
2018-09-14 11:36:37,151 INFO spawned: 'port-forward' with pid 11
2018-09-14 11:36:37,154 INFO spawned: 'novnc' with pid 12
2018-09-14 11:36:37,156 INFO spawned: 'openbox' with pid 13
2018-09-14 11:36:37,159 INFO spawned: 'x11vnc' with pid 14
2018-09-14 11:36:37,162 INFO spawned: 'android-screen-mirror' with pid 16
2018-09-14 11:36:37,165 INFO spawned: 'docker-appium' with pid 21
2018-09-14 11:36:37,168 INFO spawned: 'auto-recording' with pid 22
2018-09-14 11:36:37,170 INFO spawned: 'adb-utils' with pid 23
2018-09-14 11:36:37,172 INFO success: android-screen-mirror entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-09-14 11:36:37,180 INFO exited: android-screen-mirror (exit status 0; expected)
2018-09-14 11:36:38,217 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:38,217 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:38,217 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:38,217 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:38,217 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:38,217 INFO success: docker-appium entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:38,218 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:38,218 INFO success: adb-utils entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-14 11:36:43,180 INFO exited: auto-recording (exit status 0; expected)

[docker-compose.zip](https://github.com/butomo1989/docker-android/files/2384572/docker-compose.zip)

**Comment by jacekmusial** [comment] 2018-09-15 19:30
I have similar situation, although I don't have even terminal, just empty black screen.
The logs are interesting, because first program that exited with "1" is _xvfb (exit status 1; not expected)_ following 5 next programs returning unexpected values.

**Operating System:**
Debian 9 x64

**Docker Image**:
butomo1989/docker-android-x86-8.1 

**Docker Version**:
Docker version 18.06.1-ce, build e68fc7a

**Docker Command to start docker-android**:
git clone https://github.com/googlesamples/android-testing.git  
docker run -it --rm -v $PWD/android-testing/ui/espresso/BasicSample:/root/tmp butomo1989/docker-android-x86-8.1 tmp/gradlew build

**Logs**
2018-09-15 12:24:44,304 CRIT Supervisor running as root (no user in config file),
2018-09-15 12:24:44,307 INFO supervisord started with pid 6,
2018-09-15 12:24:45,311 INFO spawned: 'xvfb' with pid 9,
2018-09-15 12:24:45,314 INFO spawned: 'port-forward' with pid 10,
2018-09-15 12:24:45,317 INFO spawned: 'novnc' with pid 11,
2018-09-15 12:24:45,320 INFO spawned: 'openbox' with pid 12,
2018-09-15 12:24:45,323 INFO spawned: 'x11vnc' with pid 13,
2018-09-15 12:24:45,329 INFO spawned: 'android-screen-mirror' with pid 14,
2018-09-15 12:24:45,334 INFO spawned: 'docker-appium' with pid 16,
2018-09-15 12:24:45,343 INFO spawned: 'auto-recording' with pid 22,
2018-09-15 12:24:45,357 INFO spawned: 'adb-utils' with pid 26,
2018-09-15 12:24:45,363 INFO exited: xvfb (exit status 1; not expected),
2018-09-15 12:24:45,367 INFO exited: android-screen-mirror (exit status 0; expected),
2018-09-15 12:24:45,384 INFO exited: openbox (exit status 1; not expected),
2018-09-15 12:24:45,406 INFO exited: x11vnc (exit status 1; not expected),
2018-09-15 12:24:45,564 INFO exited: docker-appium (exit status 0; not expected),
2018-09-15 12:24:46,396 INFO spawned: 'xvfb' with pid 63,
2018-09-15 12:24:46,397 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-15 12:24:46,397 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-15 12:24:46,399 INFO spawned: 'openbox' with pid 64,
2018-09-15 12:24:46,400 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-15 12:24:46,400 INFO success: adb-utils entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-15 12:24:46,410 INFO spawned: 'x11vnc' with pid 67,
2018-09-15 12:24:47,553 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-15 12:24:47,553 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-15 12:24:47,553 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
2018-09-15 12:24:47,556 INFO spawned: 'docker-appium' with pid 82,
2018-09-15 12:24:47,702 INFO exited: docker-appium (exit status 0; not expected),
2018-09-15 12:24:49,707 INFO spawned: 'docker-appium' with pid 93,
2018-09-15 12:24:49,859 INFO exited: docker-appium (exit status 0; not expected),
2018-09-15 12:24:51,409 INFO exited: auto-recording (exit status 0; expected),
2018-09-15 12:24:53,414 INFO spawned: 'docker-appium' with pid 103,
2018-09-15 12:24:53,564 INFO exited: docker-appium (exit status 0; not expected),
2018-09-15 12:24:54,566 INFO gave up: docker-appium entered FATAL state, too many start retries too quickly,

![image](https://user-images.githubusercontent.com/7474972/45589924-748f9080-b92e-11e8-8882-00ea71df43e3.png)

**Comment by irux** [comment] 2018-09-17 21:57
> I have similar situation, although I don't have even terminal, just empty black screen.
> The logs are interesting, because first program that exited with "1" is _xvfb (exit status 1; not expected)_ following 5 next programs returning unexpected values.
> 
> **Operating System:**
> Debian 9 x64
> 
> **Docker Image**:
> butomo1989/docker-android-x86-8.1
> 
> **Docker Version**:
> Docker version 18.06.1-ce, build e68fc7a
> 
> **Docker Command to start docker-android**:
> git clone https://github.com/googlesamples/android-testing.git
> docker run -it --rm -v $PWD/android-testing/ui/espresso/BasicSample:/root/tmp butomo1989/docker-android-x86-8.1 tmp/gradlew build
> 
> **Logs**
> 2018-09-15 12:24:44,304 CRIT Supervisor running as root (no user in config file),
> 2018-09-15 12:24:44,307 INFO supervisord started with pid 6,
> 2018-09-15 12:24:45,311 INFO spawned: 'xvfb' with pid 9,
> 2018-09-15 12:24:45,314 INFO spawned: 'port-forward' with pid 10,
> 2018-09-15 12:24:45,317 INFO spawned: 'novnc' with pid 11,
> 2018-09-15 12:24:45,320 INFO spawned: 'openbox' with pid 12,
> 2018-09-15 12:24:45,323 INFO spawned: 'x11vnc' with pid 13,
> 2018-09-15 12:24:45,329 INFO spawned: 'android-screen-mirror' with pid 14,
> 2018-09-15 12:24:45,334 INFO spawned: 'docker-appium' with pid 16,
> 2018-09-15 12:24:45,343 INFO spawned: 'auto-recording' with pid 22,
> 2018-09-15 12:24:45,357 INFO spawned: 'adb-utils' with pid 26,
> 2018-09-15 12:24:45,363 INFO exited: xvfb (exit status 1; not expected),
> 2018-09-15 12:24:45,367 INFO exited: android-screen-mirror (exit status 0; expected),
> 2018-09-15 12:24:45,384 INFO exited: openbox (exit status 1; not expected),
> 2018-09-15 12:24:45,406 INFO exited: x11vnc (exit status 1; not expected),
> 2018-09-15 12:24:45,564 INFO exited: docker-appium (exit status 0; not expected),
> 2018-09-15 12:24:46,396 INFO spawned: 'xvfb' with pid 63,
> 2018-09-15 12:24:46,397 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2018-09-15 12:24:46,397 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2018-09-15 12:24:46,399 INFO spawned: 'openbox' with pid 64,
> 2018-09-15 12:24:46,400 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2018-09-15 12:24:46,400 INFO success: adb-utils entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2018-09-15 12:24:46,410 INFO spawned: 'x11vnc' with pid 67,
> 2018-09-15 12:24:47,553 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2018-09-15 12:24:47,553 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2018-09-15 12:24:47,553 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs),
> 2018-09-15 12:24:47,556 INFO spawned: 'docker-appium' with pid 82,
> 2018-09-15 12:24:47,702 INFO exited: docker-appium (exit status 0; not expected),
> 2018-09-15 12:24:49,707 INFO spawned: 'docker-appium' with pid 93,
> 2018-09-15 12:24:49,859 INFO exited: docker-appium (exit status 0; not expected),
> 2018-09-15 12:24:51,409 INFO exited: auto-recording (exit status 0; expected),
> 2018-09-15 12:24:53,414 INFO spawned: 'docker-appium' with pid 103,
> 2018-09-15 12:24:53,564 INFO exited: docker-appium (exit status 0; not expected),
> 2018-09-15 12:24:54,566 INFO gave up: docker-appium entered FATAL state, too many start retries too quickly,
> 
> ![image](https://user-images.githubusercontent.com/7474972/45589924-748f9080-b92e-11e8-8882-00ea71df43e3.png)

I have the same problem

**Comment by ztiandan** [comment] 2018-10-07 03:45
Same here

**Comment by ztiandan** [comment] 2018-10-09 05:46
Same here

**Comment by luisromanbcn** [comment] 2018-10-10 16:04
Same here

**Comment by sealabr** [comment] 2018-10-13 02:57
same problem

**Comment by eyal919** [comment] 2018-10-15 15:39
same

**Comment by butomo1989** [comment] 2018-10-17 08:13
Hi, 

Sorry for a late response but I cannot reproduce the error on my local machine by using Ubuntu 16.04 that you guys have. I am not sure if it is related with Linux type (e.g debian), but it would be great if you guys post the detail OS and spec of your machine that you use, so we can see on which Linux type and version this project is not able to run.

**Comment by theriley106** [comment] 2018-10-17 14:07
@butomo1989 I'm not sure if it's a setup issue on my end or just bad luck, but I'm getting this same issue on all of my machines.

HP Pavilion DV5-2070US w/ Ubuntu 16.04
Macbook Pro 15" (2012 Model) w/ El Capital (I think)
ThinkPad Yoga 14 w/ Linux Mint 18

**Comment by MatheusFaria** [comment] 2018-10-18 01:49
I was have the same issue with the API 27. I've changed to API 24 and now the emulator appears in the browser. It seems that the new kernel `kernel-ranchu`, it not supported by default for `x86_64`.

**Comment by mmatoscom** [comment] 2018-10-18 12:44
Hi guys,
the problem is the nested virtualization.
it runs fine when setup is "ubuntu 18.10 desktop - docker - kvm", however we need to automate android pipelines in the cloud, where the setup "vmware esxi server - ubuntu 16.10 vm - docker - kvm" does NOT work. Its because kvm needed to inherit some virtualization settings from the ubuntu vm, which can be made only by enabling nested virtualizaton in this vm at the vmware hypervisor layer. 
The guys from datacenter told me its "impossible" to make it work, but I have my doubts and will try further troubleshooting.

**Comment by mmatoscom** [comment] 2018-10-18 13:53
@MatheusFaria  hi bro, good day
would you mind sharing where this configuration you changed is located?
I could find something at Emulator_x86 ARG API_LEVEL=21
thanks,
Marco

**Comment by pvsenan** [comment] 2018-10-23 14:12
I have the same issue as well. I'm using windows 10. Has anyone managed to solve it ?

**Comment by MatheusFaria** [comment] 2018-10-24 03:01
@mmatoscom I've just downloaded this image `butomo1989/docker-android-x86-7.0`
But if would change the `Dockerfile` you should change the `API_LEVEL`, the `PROCESSOR`, and the `SYS_IMG`.

**Comment by pvsenan** [comment] 2018-10-24 10:34
@MatheusFaria It is not working for me. But I have tried this https://github.com/laichimirum/docker-appium-emulator for windows. The device is showing up but its not booting.

**Comment by DieterRogiest** [comment] 2018-10-24 22:14
Kubuntu 18.04 here (on a real physical pc with an intel i3 of 2012)
butomo1989/docker-android-x86-8.1
android works in http://localhost:6080 for me and rather responsive (except that its chrome browser renders some websites wrong: that android emulator is not exactly like the real thing).
Where can I find info and fixes for the chrome browser of the emulated android not working exactly like the real life version?

So it shows up on openbox: just using the scroll wheel makes the android screen disappear as you are scrolling to one of the four desktops of openbox and when you go back to desktop 1, the android screen no longer shows up (no idea whose fault is that). So I kill the emulator command /root/emulator/qemu/... and run "/bin/bash ./src/appium.sh" myself and then in openbox I rightclick and remove desktops 4, 3 and 2, leaving only desktop 1 so an accidental mouse scrolling doesn't break it again.
Then I can play with the android screen: really disappointed that the emulator cannot render the website that I have to test correctly.

Also, on some occasions when running that container the x11vnc failed to start(or was it xvfb?) and thus also no emulator process.

The x86 images are for Linux, the arm images for OSX and MS Windows. 
I ran the arm image on OSX on a brand new Macbook Pro (intel i9): it took ages for that android screen to appear and was unusable.
I tried running and pulling the x86 image in a VMware Fusion Linux VM on OSX but the download always failed after some time.
So docker-android mostly works on a real Linux pc. Curious if there are people getting it to work on OSX or MS.

**Comment by luisromanbcn** [comment] 2018-10-25 08:07
Guys, check that you are not launching the docker container with the -no-window option, if you have this option activated you will not be able to see the simulator in noVNC.

**Comment by pvsenan** [comment] 2018-10-30 20:12
@luisromanbcn I'm not using -no-window switch but still no luck :(

**Comment by Sakuragi** [comment] 2018-12-04 09:14
same problem，Has anyone managed to solve it ?

**Comment by pvsenan** [comment] 2018-12-05 15:06
@Sakuragi Nope. I kind of gave up. Trying to find some alternative

**Comment by beilunyang** [comment] 2018-12-06 04:54
have same problem, and tried all the above methods, but no solution...

**Comment by diemol** [comment] 2018-12-06 22:30
For the ones who cannot see the emulator, what do you see in the logs inside the container? Specifically in the `/var/log/supervisor/docker-android.stdout.log`?

**Comment by awgeorge** [comment] 2018-12-07 01:08
<img width="522" alt="screenshot 2018-12-07 at 01 08 06" src="https://user-images.githubusercontent.com/1777444/49621309-9bed7b00-f9bc-11e8-8032-f2a0f4f754ff.png">

**Comment by awgeorge** [comment] 2018-12-07 01:11
Not sure if this helps, but the KVM doesn't appear to be working.

<img width="501" alt="screenshot 2018-12-07 at 01 11 04" src="https://user-images.githubusercontent.com/1777444/49621392-06062000-f9bd-11e8-93df-52f5c9b9bb15.png">

**Comment by guozhanxian** [comment] 2018-12-07 10:01
> What OS are you using @awgeorge?

I have the same problem , I use win10 and Docker version 18.09.0, build 4d60db4，and docker-android-x86-9.0

**Comment by diemol** [comment] 2018-12-07 10:03
Well, please check the [README](https://github.com/butomo1989/docker-android#quick-start)
>For OSX and Windows OS, please use Virtual Machine that support Virtualization with Ubuntu OS

The emulator is extremely slow or won't work properly in any other OS, due to the nested virtualization requirement.

**Comment by awgeorge** [comment] 2018-12-07 11:35
@diemol @guozhanxian - I am trying to spin it up in Kubernetes - so not to sure what we're running the cluster on. I'll see if I can get the network guys to let me know.

**Comment by awgeorge** [comment] 2018-12-07 12:58
Looks like it's built on CoreOS Container Linux (latest stable).

**Comment by awgeorge** [comment] 2018-12-10 14:36
I think that in our case, docker is not running in privileged mode, so it’s unable to support nested virtualization, we’re planning on running some tests to get that addressed, will keep you posted.

—

**Comment by mietzen** [comment] 2019-01-08 16:57
Same here :(

Mac OSx -> VBox -> Ubunut 18.04
![untitled](https://user-images.githubusercontent.com/31704359/50846080-9645d500-136e-11e9-8cfd-491af05f64a9.png)

KVM also doesn't work like here:

> Not sure if this helps, but the KVM doesn't appear to be working.
> 
> <img alt="screenshot 2018-12-07 at 01 11 04" width="501" src="https://user-images.githubusercontent.com/1777444/49621392-06062000-f9bd-11e8-93df-52f5c9b9bb15.png">

**Comment by luisromanbcn** [comment] 2019-01-08 17:03
> Same here :(
> 
> Mac OSx -> VBox -> Ubunut 18.04

@mietzen it fails in your case because VBox doesn't allow to use Nested Virtualization so you cannot execute a simulator inside your VM, you need to use VMWare.

**Comment by XinCai** [comment] 2019-01-30 22:50
i am facing the same issue. what is the solution ?

**Comment by freekoy** [comment] 2019-02-05 06:05
you need to install kvm and turn on cpu virtualization

**Comment by antwal** [comment] 2019-03-03 20:22
the image x86-8.0 not working i see this error on log, tried on Mac Host and Linux Host but i have same problem

emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm

**Comment by deviran01** [comment] 2019-03-09 12:34
ame issue. what is the solution ?

**Comment by deviran01** [comment] 2019-03-18 14:21
https://github.com/budtmo/docker-android/issues/147#issuecomment-473713697

**Comment by Mardonov** [comment] 2019-03-20 14:14
Don't forget this:
**For OSX and Windows OS, please use Virtual Machine that support Virtualization with Ubuntu OS**
You can't run docker without virtualbox for mac/windows

**Comment by tomcangbk** [comment] 2019-03-21 06:58
Ubuntu 16.04(Real Machine)
Follow "Control Android connected to host (Emulator or Real Device)"
`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -p 4723:4723 --name android-container-appium budtmo/docker-android-real-device`
When i open localhost:6080 still only a black screen with a small window inside with name "Android Screen Monitor" and display nothing.

**Comment by budtmo** [comment] 2019-03-21 09:17
Please make sure that the Virtualization on your machine is also enabled.

**Comment by amitg25** [comment] 2019-04-12 00:42
> Don't forget this:
> **For OSX and Windows OS, please use Virtual Machine that support Virtualization with Ubuntu OS**
> You can't run docker without virtualbox for mac/windows

I am facing exact same issue and I understand this is mentioned in "READ.ME" but what does this line mean. Do we need to create a VirtualBox with Ubuntu image? and then how to use. It will be really really helpful if some can explain and provide steps for statement 
**For OSX and Windows OS, please use Virtual Machine that support Virtualization with Ubuntu OS**

**Comment by tienvx** [comment] 2019-04-15 07:59
I faced the same problem. Doing these things solve my problem:
1. Enable virtualization in BIOS https://www.youtube.com/watch?v=86zuELGMM9M
2. Set `privileged=true` in docker-compose.yaml
```

    # https://github.com/budtmo/docker-android/blob/master/docker-compose.yml
    android:
        image: budtmo/docker-android-x86-9.0
        privileged: true
        links:
            - app:example.com
        depends_on:
            - hub
        ports:
            - 6080:6080
        environment:
            - DEVICE=Samsung Galaxy S7 Edge
            - CONNECT_TO_GRID=true
            - APPIUM=true
            - SELENIUM_HOST=hub
            - MOBILE_WEB_TEST=true
            - AUTO_RECORD=false
```

**Comment by mcopjan** [comment] 2019-04-19 20:11
lucky you @tienvx. It does not work for me unfortunately. With your compose file when I open noVNC window I see running appium window, no simulator displayed. When I run "adb devices" from inside the container then there are no android devices detected :(

**Comment by tienvx** [comment] 2019-04-19 23:26
Hope these information help:
* cpu: ryzen 5 2600
* main: b450m gaming
* os: linuxmint 19.1
* I saw the same error like everyone in var/log/supervisor/docker-android.stdout.log, but after setting privileged in docker-compose.yaml, and update the bios, the error gone

**Comment by mcopjan** [comment] 2019-04-20 17:10
@tienvx Well I have Dell XPS 15 9950, Windows 10 Pro,  Virtualization enabled in BIOS, priviliged : true. Still having this issue. This ticket was created in  September 2018 @budtmo, is there remedy that would work for all of us please?

**Comment by simhem** [comment] 2019-05-15 13:28
Hello, i am also having the same issue, my emulator doesn't show up 
In the **/var/log/supervisor/docker-android.stdout.log** file, it says that i need to enable Linxu acceleration

```
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: KVM requires a CPU that supports vmx or svm
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
```

I'm using **Openshift**, and don't have admin rights on it. My question is, will my appium tests still work on this container, even without the emulator ?

**Comment by HasBert** [comment] 2019-05-16 06:56
@simhem No I don't think so. As long as your emulator inside the container is not running, you cannot do anything with the emulator.

**Comment by simhem** [comment] 2019-05-16 09:17
@HasBert Okay that's what i thought, it's seems logicial that appium needs a running device , thanks !

**Comment by linersheng** [comment] 2019-06-08 10:50
I run it on ubuntu server x64, in VMware, the same problem. 

### Where can I run x86 emulator

* Linux physical machine

* Cloud computing services (must support nested virtualization)

  **Note**: there will be a performance penalty, primarily for CPU bound workloads and I/O bound workloads.

  * [Amazon Web Services](https://aws.amazon.com/blogs/compute/running-hyper-v-on-amazon-ec2-bare-metal-instances/)

  * [Google Cloud Platform](https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances)
  
  * [IBM Cloud](https://www.ibm.com/developerworks/cloud/library/cl-nestedvirtualization/index.html)

  * [Microsoft Azure](https://azure.microsoft.com/en-us/blog/nested-virtualization-in-azure/)

* [VirtualBox](https://www.virtualbox.org/) (since 6.0.0, it started supporting nested virtualization, which could be turned on by "Enable Nested VT-x/AMD-V", but at the moment, it's only for AMD CPUs)

**Comment by Hoto-Cocoa** [comment] 2019-07-08 19:43
I tried this image in GCP, which nested-vm feature enabled.
There is no emulator screen in VNC.
![image](https://user-images.githubusercontent.com/21969938/60837798-1527a780-a204-11e9-970d-74c80b8ada2f.png)

**Comment by egandro** [comment] 2019-07-08 20:34
There should be a autorestart on exit script.

**Comment by egandro** [comment] 2019-07-08 20:35
I also would love an option it the host of the docker container can't run qemu e.g. no /dev/kvm device.

**Comment by budtmo** [comment] 2019-07-09 13:00
it might be fixed in release [1.8-p5](https://github.com/budtmo/docker-android/releases/tag/1.8-p5). Please feel free to reopen the issue

**Closed by budtmo** 2019-07-09 13:00 UTC

**Comment by Ehsanul-IBM** [comment] 2020-04-23 14:50
> Hello, i am also having the same issue, my emulator doesn't show up
> In the **/var/log/supervisor/docker-android.stdout.log** file, it says that i need to enable Linxu acceleration
> 
> ```
> emulator: CPU Acceleration: DISABLED
> emulator: CPU Acceleration status: KVM requires a CPU that supports vmx or svm
> emulator: ERROR: x86 emulation currently requires hardware acceleration!
> Please ensure KVM is properly installed and usable.
> CPU acceleration status: KVM requires a CPU that supports vmx or svm
> More info on configuring VM acceleration on Linux:
> https://developer.android.com/studio/run/emulator-acceleration#vm-linux
> General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
> ```
> 
> I'm using **Openshift** to run my containers, and don't have admin rights on it. My question is, will my appium tests still work on this container, even without the emulator ?

Did you manage to get it working on openshift?

**Comment by Ehsanul-IBM** [comment] 2020-04-23 14:51
@simhem Did you manage to get the image working on openshift?
